### ISSUE TITLE
MissingPluginException(No implementation found for method logCustomEvent on channel

### ISSUE THREAD

**Issue by avkojwer1** [khalithartmann/facebook_analytics_flutter_plugin#3]
I am using the lasted version and have followed the facebook quick start guide.
but got the error:

> 
> Installing build/app/outputs/apk/app.apk...
> I/Choreographer(12908): Skipped 55 frames!  The application may be doing too much work on its main thread.
> D/EGL_emulation(12908): eglMakeCurrent: 0xa2b863e0: ver 3 0 (tinfo 0x912d0bd0)
> Syncing files to device Android SDK built for x86...
> D/EGL_emulation(12908): eglMakeCurrent: 0xaa72f5a0: ver 3 0 (tinfo 0x90d978c0)
> D/com.facebook.FacebookSdk(12908): getGraphApiVersion: v4.0
> E/flutter (12908): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: **MissingPluginException(No implementation found for method logCustomEvent on channel** facebook_analytics_plugin)
> E/flutter (12908): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
> E/flutter (12908): <asynchronous suspension>
> E/flutter (12908): #1      FacebookAnalyticsPlugin.logCustomEvent (package:facebook_analytics_plugin/facebook_analytics_plugin.dart:25:10)
> E/flutter (12908): <asynchronous suspension>
> E/flutter (12908): #2      _MyAppState._onCustomEventButtonPressed (package:facebook_analytics_plugin_example/main.dart:53:37)
> E/flutter (12908): <asynchronous suspension>
> E/flutter (12908): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
> E/flutter (12908): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
> E/flutter (12908): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
> E/flutter (12908): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
> E/flutter (12908): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
> E/flutter (12908): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
> E/flutter (12908): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
> E/flutter (12908): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
> E/flutter (12908): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
> E/flutter (12908): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
> E/flutter (12908): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
> E/flutter (12908): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
> E/flutter (12908): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
> E/flutter (12908): #16     _rootRunUnary (dart:async/zone.dart:1136:13)
> E/flutter (12908): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> E/flutter (12908): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
> E/flutter (12908): #19     _invoke1 (dart:ui/hooks.dart:250:10)
> E/flutter (12908): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
> E/flutter (12908):

**Comment by Faiyyaz** [comment]
Same error for me. Any solution?

```
E/flutter ( 8062): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method logCustomEvent on channel facebook_analytics_plugin)
E/flutter ( 8062): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter ( 8062): <asynchronous suspension>
E/flutter ( 8062): #1      FacebookAnalyticsPlugin.logCustomEvent (package:facebook_analytics_plugin/facebook_analytics_plugin.dart:25:10)
E/flutter ( 8062): <asynchronous suspension>
E/flutter ( 8062): #2      BasicPage.logFBEvent (package:intro/base/base_stateful_widget.dart:71:29)
E/flutter ( 8062): <asynchronous suspension>
E/flutter ( 8062): #3      _SearchDomainScreenState.initState.<anonymous closure> (package:intro/screens/domain/search_domain_screen.dart:487:7)
E/flutter ( 8062): #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
E/flutter ( 8062): #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:983:9)
E/flutter ( 8062): #6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
E/flutter ( 8062): #7      _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 8062): #8      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 8062): #9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 8062): #10     _invoke (dart:ui/hooks.dart:249:10)
E/flutter ( 8062): #11     _drawFrame (dart:ui/hooks.dart:207:3)
E/flutter ( 8062): 
```

**Comment by phelipepalte** [comment]
Same here

**Comment by khal-it** [comment]
will fix soon

**Comment by mujohn26** [comment]
Same here
